# -*- coding: utf-8 -*-
"""countryinfo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uGv-76ZplTsEXWzdyql3KNpJB3tEgcE7
"""

!pip install countryinfo

from countryinfo import CountryInfo

country_name = input("Enter a country name: ")

country = CountryInfo(country_name)

try:
    print(f"Information about {country_name}:")
    print("Capital:", country.capital())
    print("Region:", country.region())
    print("Subregion:", country.subregion())
    print("Population:", country.info().get('population', 'N/A'))
    print("Area (sq km):", country.info().get('area', 'N/A'))
    print("Currencies:", country.currencies())
    print("Languages:", country.languages())
    print("Timezones:", country.timezones())
    print("Borders:", country.borders())
except:
    print("⚠️ Sorry, country information not found!")